


SQLALCHEMY_DATABASE_URI = 'sqlite:///test.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

SECRECT_TOKEN_KEY = 'xQzgrlSycaaKMQI_Sm4OFYm8F6jIrgv0NnKJmVamPzxNoixf_sR1CCH799QdBRbadlbEr0fnq_Mx303JHV971XL_ckq4yKrVmrPnVuNssWE'
SECRECT_TOKEN_EXPIRE_TIME = 500